### PR TITLE
people: add @CoelacanthusHex

### PR DESCRIPTION
**Pull request by CoelacanthusHex**

### CODE REVIEW

**Comment by MingcongBai** [comment]
Could you please move yourself above Rongwei Lin (colin4124) in the YAML?

**Comment by CoelacanthusHex** [comment]
> Could you please move yourself above Rongwei Lin (colin4124) in the YAML?

done

**Comment by liushuyu** [comment]
Sorry, can you rebase your branch?

**Comment by CoelacanthusHex** [comment]
> Sorry, can you rebase your branch?

done

**Review by liushuyu — APPROVED** [review]

**Pull request merged**
