### PR TITLE
mail: Reflect Mailcheap migration

### PR DESCRIPTION
**Pull request by thxo**

### CODE REVIEW

**Comment by liushuyu** [comment]
The `lzh` and `zh_tw` translations are probably incorrect.

Tagging @NeoChen1024 for potential corrections.

**Comment by MingcongBai** [comment]
@thxo Could you please take a look at this?

**Comment by thxo** [comment]
> @thxo Could you please take a look at this?

The only blocker comes from my incompetence in regards to traditional Chinese variants. Could use a second eye on those.

Otherwise the PR can be merged in its current state.

**Comment by MingcongBai** [comment]
Let me ring in @NeoChen1024 ...

**Pull request merged**
